name: Renovate

on: workflow_dispatch

permissions:
  contents: write
  pull-requests: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run self-hosted Renovate
        uses: renovatebot/github-action@v40.0.2
        with:
          configurationFile: renovate.json5
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          RENOVATE_PLATFORM: github
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_LOG_FILE_LEVEL: debug
          LOG_LEVEL: debug
